[2024-01-06 17:42:33,690][src.utils.utils][INFO] - [rank: 0] Enforcing tags! <cfg.extras.enforce_tags=True>
[2024-01-06 17:42:33,693][src.utils.utils][INFO] - [rank: 0] Printing config tree with Rich! <cfg.extras.print_config=True>
[2024-01-06 17:42:33,693][src.utils.rich_utils][WARNING] - [rank: 0] Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2024-01-06 17:42:33,716][__main__][INFO] - [rank: 0] Instantiating datamodule <src.data.contactpoint_datamodule.ContactPointDataModule>
[2024-01-06 17:42:33,820][__main__][INFO] - [rank: 0] Instantiating model <src.models.contactpoint_module.ContactPointLitModule>
[2024-01-06 17:42:33,848][__main__][INFO] - [rank: 0] Instantiating loggers...
[2024-01-06 17:42:33,849][src.utils.instantiators][INFO] - [rank: 0] Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2024-01-06 17:42:33,869][__main__][INFO] - [rank: 0] Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2024-01-06 17:42:33,947][__main__][INFO] - [rank: 0] Logging hyperparameters!
[2024-01-06 17:42:33,977][__main__][INFO] - [rank: 0] Starting testing!
[2024-01-06 17:42:33,993][src.utils.utils][ERROR] - [rank: 0] 
Traceback (most recent call last):
  File "/home/ghost/Documents/WorkSpace/&HXD/Trainning/VisualPropModel/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/ghost/Documents/WorkSpace/&HXD/Trainning/VisualPropModel/src/eval.py", line 75, in evaluate
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home/ghost/anaconda3/envs/softneck/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 754, in test
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/anaconda3/envs/softneck/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/anaconda3/envs/softneck/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/anaconda3/envs/softneck/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 955, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/ghost/anaconda3/envs/softneck/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 395, in _restore_modules_and_callbacks
    self.resume_start(checkpoint_path)
  File "/home/ghost/anaconda3/envs/softneck/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 79, in resume_start
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/anaconda3/envs/softneck/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 359, in load_checkpoint
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/anaconda3/envs/softneck/lib/python3.11/site-packages/lightning/fabric/plugins/io/torch_io.py", line 77, in load_checkpoint
    raise FileNotFoundError(f"Checkpoint file not found: {path}")
FileNotFoundError: Checkpoint file not found: /home/ghost/Documents/WorkSpace/&HXD/Trainning/VisualPropModel/checkpth//last.ckpt
[2024-01-06 17:42:34,089][src.utils.utils][INFO] - [rank: 0] Output dir: /home/ghost/Documents/WorkSpace/&HXD/Trainning/VisualPropModel/logs/eval/runs/2024-01-06_17-42-33
